// <auto-generated />
namespace Questionnaires.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ChangeSessionIdTypeToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeSessionIdTypeToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201309180837259_ChangeSessionIdTypeToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
